# Site settings
title: Rohit Taneja 
Linkedin: https://www.linkedin.com/in/rohit23taneja
name: Rohit Taneja

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://developer.nvidia.com/blog/author/rohit-taneja/
 - title: Google Scholar
   url: https://scholar.google.com/citations?user=CrxLWLwAAAAJ&hl=en 
 - title: GitHub
   url: https://github.com/taneja-rohit
 - title: LinkedIn
   url: https://www.linkedin.com/in/rohit23taneja

#Any buzzword skills you want to include
skills:
 - GenAI / Machine Learning
 - Microservices
 - SaaS and PaaS 
 - Business models 
 - Product management
 - API design and delivery
 - Technical Platform and Infra Architecture
 - Apache Spark 
 
#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://developer.nvidia.com/blog/author/rohit-taneja/

#Work experience is required
roles:
 - title: Senior Product Manager
   start: 2021
   end: Ongoing
   employer: NVIDIA
   description: • Leading DGX Cloud Day 2 problems for scaling workloads and data movement issues for enterprise customers. 
                • Scale via partnership in startup and enterprise landscape
                • Feature development, delivery in Agile fashion
                • Work around conferences for product launches and integrations with partners
 - title: Product Lead
   start: 2019
   end: 2021
   employer: Apple
   description: • Responsible for applying 2D ML in Apple factories (local AI)
                • Responsible for data movement to centralized data management and real time processing of model inference. 
                • Responsible for leading teams to success globally for Day 1 setup and Day 2 operations. 
                • Responsible for growing team to support operations of ML pipeline
                • Responsible for data and model drift observability and correctness in ML pipeline 
                • Responsible for scaling the product from single Apple Line of Business to across all Apple products, resulting in 100M+ savings for Apple manufacturing. 
                • Managed a team of product managers, DevOps and program managers. 
 - title: Senior Performance Engineer
   start: 2013
   end: 2016
   employer: IBM
   description: • Responsible for setting up distributed data processing pipeline using Apache Spark on Hadoop Data lake
                • Responsible for working with Major CSPs to show value of IBM solution for fastest shuffle + sorting performance. 
                • Led team to put a streaming and batch processing pipeline for enterprise use-case with Apache Spark. 
                • Worked with research to optimize IBM compute architecture for contemporary workloads like Spark in-memory processing and Deep learning workloads. 
                • Awarded patents in the process of working with research around distributed processing and helping take IBM's effort to US National Laboratories. 
                • Got eligibility for Einstein Visa and got Green Card in Einstein visa category due to work done with IBM engineering and research teams and results delivered to enhance US technology. 

#Education is required
education:
 - level: M.S., Computer Engineering 
   date: 2011
   subject: Computer Science and Engineering with Research Thesis. 
   Title: Research Assistant in NSF funded embedded computing lab
   school: North Carolina State University


intro: |
  I am a Product Manager with 15 years experience working in technology. I have worked from down in stack from Compilers for Hardware architectures to Plaform development and delivery in different go-to-market motions. I have applied technology On-prem, In enterprise Data centers at Apple and built the Cloud as-a-service model with DGX Cloud. <br/><br/>
  I enjoy building and delivering technology backed products, with a good Product Management focus and a good emphasis on good engineering principles and clean code (having worked across differing languages and platforms, I recognise that good platform and code is contextual).<br/><br/>
  I have worked in large scale enterprise roles across India and USA  as well as a mix of startup experience (including one that I started after my under graduate studies) and I am currently in Senior Product Management in Enterprise Product Group at NVIDIA.
